name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Show JDK path (for debugging)
        run: echo $env:JAVA_HOME

      - name: Build with Maven
        run: |
          $jlinkExecutable = "<jlinkExecutable>" + $env:JAVA_HOME + "\bin\jlink</jlinkExecutable>"
          (Get-Content pom.xml) |
          ForEach-Object { $_ -replace '<jlinkExecutable>.*</jlinkExecutable>', $jlinkExecutable } |
          Set-Content pom.xml
          Get-Content pom.xml
          mvn clean compile javafx:jlink 

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-zip
          path: target/app.zip