name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Show JDK path (for debugging)
        run: echo ${{ env.JAVA_HOME }} # Verifica o caminho do JDK

      - name: Build with Maven
        run: |
          sed -i "s|<jlinkExecutable>.*</jlinkExecutable>|<jlinkExecutable>${{ env.JAVA_HOME }}/bin/jlink</jlinkExecutable>|g" pom.xml
          cat pom.xml
          mvn clean compile javafx:jlink