name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Show JDK path (for debugging)
        run: echo $env:JAVA_HOME

      - name: Build with Maven
        run: |
          (Get-Content pom.xml) -replace '<jlinkExecutable>.*</jlinkExecutable>', '<jlinkExecutable>' + $env:JAVA_HOME + '\bin\jlink</jlinkExecutable>' | Set-Content pom.xml
          Get-Content pom.xml
          mvn clean compile javafx:jlink

      - name: Move ZIP to separate directory
        run: |
          mkdir apps-zip
          mv target\app.zip apps-zip\
        continue-on-error: true

      - name: Get current date
        id: get_date
        run: echo "::set-output name=date::$(Get-Date -f 'dd_MM_yyyy')"

      - name: Rename ZIP file with current date
        run: |
          $date = "${{ steps.get_date.outputs.date }}"
          ren apps-zip\app.zip "v1_app_$date.zip"

      - name: List contents of apps-zip directory
        run: |
          dir apps-zip\ /s
